### ISSUE TITLE
Duplicate register Error

### ISSUE THREAD

**Issue by MarlonAACN** [Cherrytomaten/getOutside_backend#7]
### Route:

 https://cherrytomaten.herokuapp.com/authentication/user/create/

### How to reproduce error: 

Versuch ein User zu registrieren, der bereits existiert.

### Expected behavior:

`403 Server response`

### Actual behavior:

`500 interal Server Error`
```
duplicate key value violates unique constraint "authentication_customuser_username_key"
DETAIL:  Key (username)=(testUser99) already exists.
```

**Comment by emiliadoe** [comment]
Der Bug wurde mit: "ModelClass.objects.filter(email=value).exists()" gefixt oder? @lilski190
